spring.application.name=sertao-api

spring.datasource.url=jdbc:mysql://localhost:3307/sertao_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=sertao_user
spring.datasource.password=sertao_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true