version: '3.8'

services:
  app:
    build: .
    container_name: sertao-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # Sobrescreve a URL para usar o nome do serviço 'db' dentro da rede do Docker
      - DB_URL=jdbc:mysql://db:3306/${DB_DATABASE}

  db:
    image: mysql:8.0
    container_name: sertao-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
