services:
  mysql:
    image: mysql:8.0
    container_name: sertao-mysql
    environment:
      MYSQL_DATABASE: sertao_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sertao_user
      MYSQL_PASSWORD: sertao_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  sertao-api:
    image: sertao-api
    container_name: sertao-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sertao-mysql:3306/sertao_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: sertao_user
      SPRING_DATASOURCE_PASSWORD: sertao_password
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
